### PR TITLE
Fix eviction of session states

### LINKED ISSUE #3: Session._evict_oldest_session_state() fails as oldest is undefined (Error code 8391)
There error reports where the eviction of the latest session state raises and error (hased to code 8391) as the state reduction returns null causing the decryption of a message to fail.

https://github.com/wireapp/proteus.js/blob/c07092b66b84e107558e0ad3985ef1b7337686bd/src/proteus/session/Session.coffee#L166

### PR DESCRIPTION
**Pull request by ffflorian**
Rewrote the eviction of session states when a `session` has too many states (right now `> 100`) based on the [Rust source](https://github.com/wireapp/proteus/blob/master/src/internal/session.rs#L540) and created a test, which is also based on the [Rust source test](https://github.com/wireapp/proteus/blob/master/src/internal/session.rs#L1417).

Fixes #3.

### CODE REVIEW

File: test/session/SessionSpec.coffee [hunk 1]
```diff
@@ -772,3 +772,45 @@ describe 'Session', ->
...
+
+    alice = null
+    bob = null
+    hello_bob = null
+
+    Proteus.session.Session.init_from_prekey alice_ident, bob_bundle 1, bob_store
+    .then (s) ->
+      alice = s
+      alice.encrypt 'Hello Bob!'
+
```
Comment (bennyn) [inline test/session/SessionSpec.coffee]: Please remove empty lines between `.then` blocks.

File: test/session/SessionSpec.coffee [hunk 2]
```diff
@@ -772,3 +772,45 @@ describe 'Session', ->
...
+    bob_store = new TestStore Proteus.keys.PreKey.generate_prekeys 0, (Proteus.session.Session.MAX_SESSION_STATES + 2)
+
+    bob_bundle = (i, store) -> Proteus.keys.PreKeyBundle.new bob_ident.public_key, store.prekeys[i]
+
+    alice = null
+    bob = null
+    hello_bob = null
+
+    Proteus.session.Session.init_from_prekey alice_ident, bob_bundle 1, bob_store
+    .then (s) ->
```
Comment (bennyn) [inline test/session/SessionSpec.coffee]: Please use proper naming (like `session`) instead of cryptic letters (like `s`).

File: test/session/SessionSpec.coffee [hunk 3]
```diff
@@ -772,3 +772,45 @@ describe 'Session', ->
...
+          Proteus.session.Session.init_from_prekey(alice_ident, bob_bundle(i + 2, bob_store))
+          .then (s) ->
+            alice = s
+            alice.encrypt 'Hello Bob!'
+
+          .then (m) ->
+            hello_bob = m
+            assert_decrypt 'Hello Bob!', bob.decrypt bob_store, hello_bob
+
+          .then((() -> resolve()), (err) -> reject(err))))
```
Comment (bennyn) [inline test/session/SessionSpec.coffee]: Evaluate if this can be done with:

```coffeescript
.then resolve
.catch reject
```

Instead of having an army of brackets like `.then((() -> resolve()), (err) -> reject(err))))`.

File: test/session/SessionSpec.coffee [hunk 4]
```diff
@@ -772,3 +772,45 @@ describe 'Session', ->
...
+    alice = null
+    bob = null
+    hello_bob = null
+
+    Proteus.session.Session.init_from_prekey alice_ident, bob_bundle 1, bob_store
+    .then (s) ->
+      alice = s
+      alice.encrypt 'Hello Bob!'
+
+    .then (m) ->
```
Comment (bennyn) [inline test/session/SessionSpec.coffee]: Please use proper naming (like `message`) instead of cryptic letters (like `m`).

File: src/proteus/session/Session.coffee [hunk 5]
```diff
@@ -149,19 +149,12 @@ module.exports = class Session
     @_evict_oldest_session_state()
 
   _evict_oldest_session_state: ->
-    states = ([k, v] for k, v in @session_states \
-                          when k.toString() isnt @session_tag.toString())
+    oldest = Object.keys(@session_states)
```
Comment (bennyn) [inline src/proteus/session/Session.coffee]: Parentheses can be dropped, just use: `oldest = Object.keys @session_states`.

**Comment by ffflorian** [comment]
Sorry, first PR commit message should actually be `Fix eviction of session states`. If this PR gets accepted, I'll change the merge commit message accordingly.

**Comment by bennyn** [comment]
Go for it! 😎

**Comment by bennyn** [comment]
🎉

File: test/session/SessionSpec.coffee [hunk 6]
```diff
@@ -772,3 +772,49 @@ describe 'Session', ->
...
+      hello_bob = message
+      assert_init_from_message bob_ident, bob_store, hello_bob, 'Hello Bob!'
+    .then (session) ->
+      bob = session
+      assert obj_size(bob.session_states) is 1
+
+      Promise.all(
+        [0..(Proteus.session.Session.MAX_SESSION_STATES - 1)].map (obj, index) ->
+          new Promise (resolve, reject) ->
+            Proteus.session.Session.init_from_prekey alice_ident, bob_bundle (index + 2), bob_store
```
Comment (herrmannplatz) [inline test/session/SessionSpec.coffee]: `init_from_prekey ` return a promise or? So there is no need to spawn a new promise here. Then you can also get rid of the then -> resolve, catch -> reject

Comment (ffflorian) [inline test/session/SessionSpec.coffee]: You are right, my mistake. Should I create a new PR for that?

Comment (herrmannplatz) [inline test/session/SessionSpec.coffee]: The test is fine, so you might just do that in the vanilla branch.
